### ISSUE TITLE
HELLO

### ISSUE THREAD

**Issue by Koala3353** [Overkill10117/Stuff#2]
### ADD MY BOT USING THIS LINK PEOPLE
https://discord.gg/BNRxHb77

### UPVOTE ME HERE

https://discord.bots.gg/bots/761072632958681099
https://discordbotlist.com/bots/legendary-bot-2634

**Comment by Koala3353** [comment]
YAY

**Comment by Overkill10117** [comment]
why here

**Comment by Koala3353** [comment]
WHY NOT?

**Comment by Overkill10117** [comment]
haha
