### ISSUE TITLE
GUYS REMEMBER TO UPVOTE MY BOT TO SHOW SUPPORT

### ISSUE THREAD

**Issue by Koala3353** [Overkill10117/Stuff#4]
Upvote / Invite Link
https://discordbotlist.com/bots/legendary-bot-2634

Invite Link to Legendary Bot Server
https://discord.gg/rEyEjqD7NJ

REMEMBER TO ADD MY BOT ALSO!!!

CREDITS :
 @Overkill1011 for hosting the advertisement!!!

**Comment by Overkill10117** [comment]
me too

**Comment by Overkill10117** [comment]
ADD MY BOTS HERE
[https://discord.com/oauth2/authorize?client_id=795555997337780224&scope=bot&permissions=8](https://discord.com/oauth2/authorize?client_id=795555997337780224&scope=bot&permissions=8)
[https://discord.com/oauth2/authorize?client_id=783925909987131402&scope=bot&permissions=8](https://discord.com/oauth2/authorize?client_id=783925909987131402&scope=bot&permissions=8)
[https://discord.com/oauth2/authorize?client_id=783925909987131402&scope=bot&permissions=8](https://discord.com/oauth2/authorize?client_id=783925909987131402&scope=bot&permissions=8)

UPVOTE MY BOTS HERE!!
[discord.ly/spam-bot](discord.ly/spam-bot)
[discord.ly/spam-bot-2](discord.ly/spam-bot-2)
[discord.ly/ultimate-spam-bot](discord.ly/ultimate-spam-bot)
