### ISSUE TITLE
Reminders

### ISSUE THREAD

**Issue by Koala3353** [Overkill10117/Stuff#7]
Remember to....
1.) Add my bot
2.) Join my [discord](https://discord.gg/rEyEjqD7NJ)
3.) [Upvote](https://discordbotlist.com/bots/legendary-bot-2634) my bot

**Comment by Overkill10117** [comment]
Remember to....
1.) Add my bot
2.) Join my discord - [https://discord.gg/msmTXzks](https://discord.gg/msmTXzks)
3.) Upvote my bot
