### ISSUE TITLE
FUN FACT OF THE DAY

### ISSUE THREAD

**Issue by Koala3353** [Overkill10117/Stuff#8]
FUN FACT OF THE DAY IS.....

1.) The [legendary bot](https://discordbotlist.com/bots/legendary-bot-2634) is made by using Java
2.) Created by me
3.) Discord server link [here](https://discord.gg/rEyEjqD7NJ)
4.) Link to my [code](https://github.com/Doom306/Discord-bot/tree/main/src/main/java)

**Comment by Overkill10117** [comment]
ok
